export const SOCKET_CONNECT = 'ENAIL/SOCKET/CONNECT';
export const SOCKET_CONNECTED = 'ENAIL/SOCKET/CONNECTED';
export const SOCKET_DISCONNECTED = 'ENAIL/SOCKET/DISCONNECTED';
export const SOCKET_EMIT_STATE = 'ENAIL/EMIT/STATE';

export const SCRIPTS_REQUEST = 'ENAIL/SCRIPTS/REQUEST';
export const SCRIPTS_RESPONSE = 'ENAIL/SCRIPTS/RESPONSE';
export const SCRIPTS_ERROR = 'ENAIL/SCRIPTS/ERROR';

export const SETSP_REQUEST = 'ENAIL/SETSP/REQUEST';
export const SETSP_RESPONSE = 'ENAIL/SETSP/RESPONSE';
export const SETSP_ERROR = 'ENAIL/SETSP/ERROR';

export const TOGGLE_STATE_REQUEST = 'ENAIL/TOGGLESTATE/REQUEST';
export const TOGGLE_STATE_RESPONSE = 'ENAIL/TOGGLESTATE/RESPONSE';
export const TOGGLE_STATE_ERROR = 'ENAIL/TOGGLESTATE/ERROR';

export const RUN_SCRIPT_REQUEST = 'ENAIL/RUN_SCRIPT/REQUEST';
export const RUN_SCRIPT_RESPONSE = 'ENAIL/RUN_SCRIPT/RESPONSE';
export const RUN_SCRIPT_ERROR = 'ENAIL/RUN_SCRIPT/ERROR';

export const END_SCRIPT_REQUEST = 'ENAIL/END_SCRIPT/REQUEST';
export const END_SCRIPT_RESPONSE = 'ENAIL/END_SCRIPT/RESPONSE';
export const END_SCRIPT_ERROR = 'ENAIL/END_SCRIPT/ERROR';

export const SERVICE_FOUND = 'ENAIL/SERVICE/FOUND';

export const LOCAL_STORAGE_FCENAIL_SERVICE_URL = 'FCENAIL:SERVICEURL';