export const SOCKET_CONNECT = 'ENAIL/SOCKET/CONNECT';
export const SOCKET_CONNECTED = 'ENAIL/SOCKET/CONNECTED';
export const SOCKET_DISCONNECTED = 'ENAIL/SOCKET/DISCONNECTED';
export const SOCKET_EMIT_STATE = 'ENAIL/EMIT/STATE';

export const SCRIPTS_REQUEST = 'ENAIL/SCRIPTS/REQUEST';
export const SCRIPTS_RESPONSE = 'ENAIL/SCRIPTS/RESPONSE';
export const SCRIPTS_ERROR = 'ENAIL/SCRIPTS/ERROR';

export const SETSP_REQUEST = 'ENAIL/SETSP/REQUEST';
export const SETSP_RESPONSE = 'ENAIL/SETSP/RESPONSE';
export const SETSP_ERROR = 'ENAIL/SETSP/ERROR';

export const TOGGLE_STATE_REQUEST = 'ENAIL/TOGGLESTATE/REQUEST';
export const TOGGLE_STATE_RESPONSE = 'ENAIL/TOGGLESTATE/RESPONSE';
export const TOGGLE_STATE_ERROR = 'ENAIL/TOGGLESTATE/ERROR';

export const RUN_SCRIPT_REQUEST = 'ENAIL/RUN_SCRIPT/REQUEST';
export const RUN_SCRIPT_RESPONSE = 'ENAIL/RUN_SCRIPT/RESPONSE';
export const RUN_SCRIPT_ERROR = 'ENAIL/RUN_SCRIPT/ERROR';

export const END_SCRIPT_REQUEST = 'ENAIL/END_SCRIPT/REQUEST';
export const END_SCRIPT_RESPONSE = 'ENAIL/END_SCRIPT/RESPONSE';
export const END_SCRIPT_ERROR = 'ENAIL/END_SCRIPT/ERROR';

export const SET_SCRIPT_REQUEST = 'ENAIL/SET_SCRIPT/REQUEST';
export const SET_SCRIPT_RESPONSE = 'ENAIL/SET_SCRIPT/RESPONSE';
export const SET_SCRIPT_ERROR = 'ENAIL/SET_SCRIPT/ERROR';

export const SERVICE_FOUND = 'ENAIL/SERVICE/FOUND';
export const RECONNECT = 'ENAIL/SERVICE/RECONNECT';

export const LOCAL_STORAGE_FCENAIL_SERVICE_URL = 'FCENAIL:SERVICEURL';
export const LOCAL_STORAGE_FCENAIL_KEY = 'FCENAIL:AUTH';

export const LOAD_SAVED_STATE_REQUEST = 'ENAIL/SAVED_STATE/LOAD/REQUEST';
export const LOAD_SAVED_STATE_RESPONSE = 'ENAIL/SAVED_STATE/LOAD/RESPONSE';
export const LOAD_SAVED_STATE_ERROR = 'ENAIL/SAVED_STATE/LOAD/ERROR';

export const PERSIST_SAVED_STATE_REQUEST = 'ENAIL/SAVED_STATE/PERSIST/REQUEST';
export const PERSIST_SAVED_STATE_RESPONSE = 'ENAIL/SAVED_STATE/PERSIST/RESPONSE';
export const PERSIST_SAVED_STATE_ERROR = 'ENAIL/SAVED_STATE/PERSIST/ERROR';

export const PASSPHRASE_GENERATE_REQUEST = 'ENAIL/PASSPHRASE/GENERATE/REQUEST';
export const PASSPHRASE_GENERATE_RESPONSE = 'ENAIL/PASSPHRASE/GENERATE/RESPONSE';
export const PASSPHRASE_GENERATE_ERROR = 'ENAIL/PASSPHRASE/GENERATE/ERROR';

export const PASSPHRASE_VERIFY_REQUEST = 'ENAIL/PASSPHRASE/VERIFY/REQUEST';
export const PASSPHRASE_VERIFY_RESPONSE = 'ENAIL/PASSPHRASE/VERIFY/RESPONSE';
export const PASSPHRASE_VERIFY_ERROR = 'ENAIL/PASSPHRASE/VERIFY/ERROR';

export const LOAD_TOKEN = 'ENAIL/TOKEN/LOAD';
export const TOKEN_LOADED = 'ENAIL/TOKEN/LOADED';